CREATE TABLE IF NOT EXISTS aktivt_vedtak
(
    aktivt_vedtak_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vedtak_id integer NOT NULL,
    sak_id varchar(20),
    soknadsbarn_id varchar(20) NOT NULL,
    mottaker_id varchar(20) NOT NULL,
    vedtak_dato_siste_vedtak date NOT NULL,
    vedtak_dato_siste_manuelle_vedtak date NOT NULL,
    vedtak_type varchar(20) NOT NULL,
    belop float NOT NULL,
    valutakode varchar(10) NOT NULL,
    resultatkode varchar(255) NOT NULL,
    mottaker_sivilstand_siste_manuelle_vedtak varchar(20) NOT NULL,
    mottaker_antall_barn_siste_manuelle_vedtak integer NOT NULL,
    soknadsbarn_bostedsstatus varchar(20) NOT NULL,
    soknadsbarn_fodselsdato date NOT NULL,
    soknadsbarn_har_unntakskode boolean DEFAULT false NOT NULL,
    opprettet_av varchar(20) NOT NULL,
    opprettet_timestamp timestamp DEFAULT now() NOT NULL,
    CONSTRAINT aktivt_vedtak_pkey PRIMARY KEY (aktivt_vedtak_id)
);
